name: Test md to jobsummary

on:
  pull_request:
  workflow_dispatch:
    branches:
      - main
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      - name: 'test'
        if: github.event_name != 'pull_request' && github.actor != 'dependabot[bot]'
        uses: janpk/md-to-jobsummary@v1
        with:
          action: jobsummary
          file: ./README.md
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: 'test-pr'
        if: github.event_name == 'pull_request' && github.actor != 'dependabot[bot]'
        uses: janpk/md-to-jobsummary@v1
        with:
          action: pullrequest
          file: ./README.md
          github-token: ${{ secrets.GITHUB_TOKEN }}
