name: Test Badges

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  create-badges:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: 'Style : flat'
        uses: janpk/badge-to-path@main
        with:
          label: Hello
          message: World
          path: badges/flat.svg
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Style : flat-square'
        uses: janpk/badge-to-path@main
        with:
          label: Hello
          message: World
          style: flat-square
          path: badges/flat-square.svg
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Style : for-the-badge'
        uses: janpk/badge-to-path@main
        with:
          label: Hello
          message: World
          style: for-the-badge
          path: badges/forthebadge.svg
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Style : plastic'
        uses: janpk/badge-to-path@main
        with:
          label: Hello
          message: World
          style: plastic
          path: badges/plastic.svg
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Style : social'
        uses: janpk/badge-to-path@main
        with:
          label: Hello
          message: World
          style: social
          path: badges/social.svg
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit the badge (if it changed)
        if: github.ref == 'refs/heads/main'
        run: |
          cd badges
          if [[ `git status --porcelain *.svg` ]]; then
            git config --global user.email "vampyr.geistlig_0j@icloud.com"
            git config --global user.name "Badge Gen"
            git add *.svg
            git commit -m "Autogenerated badge" --allow-empty
            git push
          fi
      
