name: Test md to jobsummary

on:
  workflow_dispatch:
    branches:
      - main
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      - name: 'test'
        uses: janpk/md-to-jobsummary@v1.1
        with:
          file: ./README.md
          github-token: ${{ secrets.GITHUB_TOKEN }}

