name: Test Badges

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  create-badges:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: 'Style : flat'
        uses: janpk/badge-to-path@v1
        with:
          label: Hello
          message: World
          path: badges/flat.svg
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Style : flat-square'
        uses: janpk/badge-to-path@v1.0.0
        with:
          label: Hello
          message: World
          style: flat-square
          path: badges/flat-square.svg
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Style : for-the-badge'
        uses: janpk/badge-to-path@main
        with:
          label: Hello
          message: World
          style: for-the-badge
          path: badges/forthebadge.svg
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Style : plastic'
        uses: janpk/badge-to-path@main
        with:
          label: Hello
          message: World
          style: plastic
          path: badges/plastic.svg
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Style : social'
        uses: janpk/badge-to-path@main
        with:
          label: Hello
          message: World
          style: social
          path: badges/social.svg
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Color : brightgreen'
        uses: janpk/badge-to-path@main
        with:
          label: Hello
          message: brightgreen
          messageColor: brightgreen
          path: badges/color-brightgreen.svg
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Color : green'
        uses: janpk/badge-to-path@main
        with:
          label: Hello
          message: green
          messageColor: green
          path: badges/color-green.svg
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Color : yellow'
        uses: janpk/badge-to-path@main
        with:
          label: Hello
          message: yellow
          messageColor: yellow
          path: badges/color-yellow.svg
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Color : yellowgreen'
        uses: janpk/badge-to-path@main
        with:
          label: Hello
          message: yellowgreen
          messageColor: yellowgreen
          path: badges/color-yellowgreen.svg
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Color : orange'
        uses: janpk/badge-to-path@main
        with:
          label: Hello
          message: orange
          messageColor: orange
          path: badges/color-orange.svg
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Color : red'
        uses: janpk/badge-to-path@main
        with:
          label: Hello
          message: red
          messageColor: red
          path: badges/color-red.svg
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Color : blue'
        uses: janpk/badge-to-path@main
        with:
          label: Hello
          message: blue
          messageColor: blue
          path: badges/color-blue.svg
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Color : grey'
        uses: janpk/badge-to-path@main
        with:
          label: Hello
          message: grey
          messageColor: grey
          path: badges/color-grey.svg
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Color : lightgrey'
        uses: janpk/badge-to-path@main
        with:
          label: Hello
          message: lightgrey
          messageColor: lightgrey
          path: badges/color-lightgrey.svg
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Color : gray'
        uses: janpk/badge-to-path@main
        with:
          label: gray
          message: gray
          messageColor: gray
          path: badges/color-gray.svg
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Color : lightgray'
        uses: janpk/badge-to-path@main
        with:
          label: Hello
          message: lightgray
          messageColor: lightgray
          path: badges/color-lightgray.svg
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Color : critical'
        uses: janpk/badge-to-path@main
        with:
          label: Hello
          message: critical
          messageColor: critical
          path: badges/color-critical.svg
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Color : important'
        uses: janpk/badge-to-path@main
        with:
          label: Hello
          message: important
          messageColor: important
          path: badges/color-important.svg
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Color : success'
        uses: janpk/badge-to-path@main
        with:
          label: Hello
          message: success
          messageColor: success
          path: badges/color-success.svg
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Color : informational'
        uses: janpk/badge-to-path@main
        with:
          label: Hello
          message: informational
          messageColor: informational
          path: badges/color-informational.svg
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Color : inactive'
        uses: janpk/badge-to-path@main
        with:
          label: Hello
          message: inactive
          messageColor: inactive
          path: badges/color-inactive.svg
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Color : ff69b4'
        uses: janpk/badge-to-path@main
        with:
          label: Hello
          message: ff69b4
          messageColor: ff69b4
          path: badges/color-ff69b4.svg
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Color : 9cf'
        uses: janpk/badge-to-path@main
        with:
          label: Hello
          message: 9cf
          messageColor: 9cf
          path: badges/color-9cf.svg
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Link'
        uses: janpk/badge-to-path@main
        with:
          label: Hello
          message: GitHub
          link: https://github.com
          path: badges/githublink.svg
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Logo'
        uses: janpk/badge-to-path@main
        with:
          label: Hello
          message: GitHub
          logo: github
          path: badges/githublogo.svg
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: 'LogoWidth'
        uses: janpk/badge-to-path@main
        with:
          label: Hello
          message: GitHub
          logo: github
          logoWidth: 200
          path: badges/githublogowidth.svg
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Logo with Link'
        uses: janpk/badge-to-path@main
        with:
          label: Hello
          message: GitHub
          link: https://github.com
          logo: github
          path: badges/githublogolink.svg
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit the badge (if it changed)
        if: github.ref == 'refs/heads/main'
        run: |
          cd badges
          if [[ `git status --porcelain *.svg` ]]; then
            git config --global user.email "vampyr.geistlig_0j@icloud.com"
            git config --global user.name "Badge Gen"
            git add *.svg
            git commit -m "Autogenerated badge" --allow-empty
            git push
          fi
      
